export const Data = [
  {
    comment_count: 20,
    context_chapter: "Psalm 23: 'The Lord is my shepherd, I shall not want...'",
    context_chapter_link: "https://www.bible.com/en/bible/psalm.23",
    date: "2025-01-02",
    id: "12346",
    is_favorite: false,
    reflection: "This verse emphasizes God's provision and care for His people.",
    reflection_link: "https://www.bible.com/en/reflections/psalm.23",
    verse: "The Lord is my shepherd; I shall not want.",
    verse_reference: "Psalm 23:1",
    video_link: "https://www.youtube.com/watch?v=xrAdbYTgY8k",
  }, {
    comment_count: 5,
    context_chapter: "Matthew 6: 'Do not be anxious about tomorrow...'",
    context_chapter_link: "https://www.bible.com/en/bible/matthew.6.34",
    date: "2025-01-01",
    id: "12347",
    is_favorite: true,
    reflection: "This verse encourages us to trust God with our worries.",
    reflection_link: "https://www.bible.com/en/reflections/matthew.6.34",
    verse: "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
    verse_reference: "Matthew 6:34",
    video_link: "https://www.youtube.com/watch?v=abc123xyz",
  },{
    comment_count: 8,
    context_chapter: "Philippians 4: 'Rejoice in the Lord always...'",
    context_chapter_link: "https://www.bible.com/en/bible/philippians.4.4",
    date: "2024-12-31",
    id: "12348",
    is_favorite: false,
    reflection: "Rejoicing in the Lord brings peace and joy despite circumstances.",
    reflection_link: "https://www.bible.com/en/reflections/philippians.4.4",
    verse: "Rejoice in the Lord always; again I will say, rejoice.",
    verse_reference: "Philippians 4:4",
    video_link: "https://www.youtube.com/watch?v=joyful123abc",
  },{
    comment_count: 12,
    context_chapter: "Isaiah 40: 'Those who wait for the Lord shall renew their strength...'",
    context_chapter_link: "https://www.bible.com/en/bible/isaiah.40.31",
    date: "2025-01-03",
    id: "12349",
    is_favorite: true,
    reflection: "Waiting on the Lord provides renewed strength and perseverance.",
    reflection_link: "https://www.bible.com/en/reflections/isaiah.40.31",
    verse: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
    verse_reference: "Isaiah 40:31",
    video_link: "https://www.youtube.com/watch?v=isaiah123456",
  }
];
